# Generated by Django 4.2.3 on 2023-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nomde',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
